services:
  # vaultwarden:
  #   image: vaultwarden/server:latest
  #   container_name: vaultwarden
  #   restart: unless-stopped
  #   environment:
  #     - SIGNUPS_ALLOWED=true
  #     - DOMAIN=https://vault.${CLOUDFLARE_DOMAIN}
  #   volumes:
  #     - ./data/vault:/data

  # immich_server:
  #   image: ghcr.io/immich-app/immich-server:v2
  #   container_name: immich_server
  #   restart: always
  #   volumes:
  #     - ./data/photos:/usr/src/app/upload
  #   env_file: immich.example.env

  # n8n:
  #   image: n8nio/n8n
  #   container_name: n8n
  #   restart: unless-stopped
  #   environment:
  #     - N8N_HOST=home.${CLOUDFLARE_DOMAIN}
  #     - N8N_PROTOCOL=https
  #     - WEBHOOK_URL=https://home.${CLOUDFLARE_DOMAIN}/
  #   volumes:
  #     - ./config/n8n:/home/node/.n8n

  unmanic:
    image: josh5/unmanic:latest
    container_name: unmanic
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ./config/unmanic:/config
      - ./data/movies:/library/movies
      - ./data/tvshows:/library/tvshows
      - ./cache/unmanic:/tmp/unmanic
    ports:
      - 8888:8888

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 8096:8096
    volumes:
      - ./config/jellyfin:/config
      - ./data/movies:/data/movies
      - ./data/tvshows:/data/tvshows

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    ports:
      - 6767:6767
    volumes:
      - ./config/bazarr:/config
      - ./data/movies:/movies
      - ./data/tvshows:/tv

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 7878:7878
    volumes:
      - ./config/radarr:/config
      - ./data/movies:/movies
      - ./data/downloads:/downloads

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config/sonarr:/config
      - ./data/tvshows:/tv
      - ./data/downloads:/downloads
    ports:
      - 8989:8989

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - 9696:9696
    volumes:
      - ./config/prowlarr:/config

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ./config/qbittorrent:/config
      - ./data/downloads:/downloads
