services:
  dns-resolver:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_dns
    restart: unless-stopped
    # We fix the IP so we can point Prowlarr to it directly
    networks:
      secure-pipe:
        ipv4_address: 172.20.0.53
    command: proxy-dns --address 0.0.0.0 --port 53 --upstream https://1.1.1.1/dns-query --upstream https://1.0.0.1/dns-query

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    dns:
      - 172.20.0.53
    networks:
      - secure-pipe
    depends_on:
      - dns-resolver
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - 9696:9696
    volumes:
      - ./config/prowlarr:/config

  unmanic:
    image: josh5/unmanic:latest
    container_name: unmanic
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ./config/unmanic:/config
      - ./data/movies:/library/movies
      - ./data/tvshows:/library/tvshows
      - ./cache/unmanic:/tmp/unmanic
    ports:
      - 8888:8888

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 8096:8096
    volumes:
      - ./config/jellyfin:/config
      - ./data/movies:/data/movies
      - ./data/tvshows:/data/tvshows

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    ports:
      - 6767:6767
    volumes:
      - ./config/bazarr:/config
      - ./data/movies:/movies
      - ./data/tvshows:/tv

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 7878:7878
    volumes:
      - ./config/radarr:/config
      - ./data/movies:/movies
      - ./data/downloads:/downloads

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config/sonarr:/config
      - ./data/tvshows:/tv
      - ./data/downloads:/downloads
    ports:
      - 8989:8989

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ./config/qbittorrent:/config
      - ./data/downloads:/downloads

networks:
  secure-pipe:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
